### ISSUE TITLE
请教采用深度学习方法处理有关MRI图像的分类问题

### ISSUE THREAD

**Issue by homingZhang** [jastarex/DeepLearningCourseCodes#2]
戎老师，你好。
我是深度学习课程的学生，张家宁。
想请教如下问题：
**我的目的**：大脑磁共振（MRI）图像的二分类；
**处理的数据**：大脑MRI数据，经过我的预处理（MRI数据特有的预处理），每个被试的图像维度是：121X145X121。目前患病和健康被试各有60例。
**采用的方法**：之前采用的传统特征和SVM分类的方法，准确率有80%。目前想尝试采用深度学习的方法。目前仅简单尝试了Alexnetwork，网络结构基本都没变。
**遇到的问题**：
1）大脑结构MRI图像很难直观看到病灶区，医生也基本无法直接看到。所以，无法根据病灶等信息来设计网络等；戎老师针对这种情况，如何来设计自己的网络呢？
2）针对输入深度较大的图像（121，而不是之前的单通道灰度或者RGB图像），第一层的卷积核深度也要和其保持一致吗？（您课上说，要基本保持一致）

**Comment by ionvision** [comment]
你好，我们最近也在做磁共振图像的注意力与显著性分布问题，很多时候需要根据实际医生的眼球追踪过程(eye tracking)来采集数据，对于上述问题：
1）直接用正常的图像分类网络应该就可以，具体的结构设计可以参照一些MICCAI 2017的paper: 
http://www.miccai2017.org/
http://docs.wixstatic.com/ugd/9f28fb_14b7f10c74054c31a72b997948e63d8c.pdf
2）是的，深度必须保持一致。当然因为初始深度比较大，可以考虑使用group convolution与depth-wise convolution来减少计算量。
