### ISSUE TITLE
Bug report: nearest_neighbor_tf

### ISSUE THREAD

**Issue by johnnychen94** [jastarex/DeepLearningCourseCodes#5]
In **In[3]** of [nearest_neighbor_tf.ipynb](https://github.com/jastarex/DeepLearningCourseCodes/blob/master/02_Logistic_regression_and_multilayer_perceptron/nearest_neighbor_tf.ipynb)
`nn_index = sess.run(pred, feed_dict={xtr: Xtr, xte: Xte[i , : ]})`
should be replaced by
`nn_index = sess.run(pred, feed_dict={xtr: Xtr, xte: Xte[i]})`

**Comment by ionvision** [comment]
这里的维度没有问题，Xte包含了一整个mini-batch里的图片数据
